name: 04 - Using Actions

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

        
      - name: Printing Folders
        run: |
          echo "Current working directory:"
          pwd
          echo "Repo root contents:"
          ls -la
          echo "Exercise folder contents:"
          ls -la 04-using-actions
          echo "React app folder contents:"
          ls -la 04-using-actions/react-app
