# name: 04 - Using Actions

# on:
#   push:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4




#       - name: Printing Folders
#         run: |
#           echo "Current working directory:"
#           pwd
#           echo "Repo root contents:"
#           ls -la
#           echo "Non-workflow files:"
#           ls -la non_workflow_files
#           echo "React app folder contents:"
#           ls -la react-app

name: 04 - Using Actions

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm ci
        working-directory: react-app
